
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: root
    database-platform: org.hibernate.dialect.MySQLDialect
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update