
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
#  config:
#    import: aws-secretsmanager:/secret/testsecret
